
import { Inter } from "next/font/google";
import "./globals.css";
import DockBar from "@/components/DockBar";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <DockBar />
      </body>
    </html>
  );
}
